config/routes.rb
Rails.application.routes.draw do
  resources :breeds
  resources :dogs

  root 'dogs#index'

end

app/models/breed.rb
class Breed < ActiveRecord::Base

	has_many :dogs

end

app/models/dog.rb
class Dog < ActiveRecord::Base

	belongs_to :breed

	mount_uploader :picture, PictureUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  before_action :set_breed, only: [:show, :edit, :update, :destroy]

  # GET /breeds
  # GET /breeds.json
  def index
    @breeds = Breed.all
  end

  # GET /breeds/1
  # GET /breeds/1.json
  def show
  end

  # GET /breeds/new
  def new
    @breed = Breed.new
  end

  # GET /breeds/1/edit
  def edit
  end

  # POST /breeds
  # POST /breeds.json
  def create
    @breed = Breed.new(breed_params)

    respond_to do |format|
      if @breed.save
        format.html { redirect_to @breed, notice: 'Breed was successfully created.' }
        format.json { render :show, status: :created, location: @breed }
      else
        format.html { render :new }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breeds/1
  # PATCH/PUT /breeds/1.json
  def update
    respond_to do |format|
      if @breed.update(breed_params)
        format.html { redirect_to @breed, notice: 'Breed was successfully updated.' }
        format.json { render :show, status: :ok, location: @breed }
      else
        format.html { render :edit }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeds/1
  # DELETE /breeds/1.json
  def destroy
    @breed.destroy
    respond_to do |format|
      format.html { redirect_to breeds_url, notice: 'Breed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breed
      @breed = Breed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breed_params
      params.require(:breed).permit(:name, :description)
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    if params[:sort_by]
      @dogs = Dog.all.sort_by{ |d| d.send(params[:sort_by]) }
    elsif params[:babies]
      @dogs = Dog.all.select{|d| d.age < 5 }
    elsif params[:pictures]
      @dogs = Dog.all.select{|d| !(d.picture_url.blank?) }
    elsif params[:breed_id]
      @dogs = Breed.find(params[:breed_id]).dogs
    else
      @dogs = Dog.all
    end
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :age, :picture, :breed_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/breeds/_form.html.erb
<%= form_for(@breed) do |f| %>
  <% if @breed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@breed.errors.count, "error") %> prohibited this breed from being saved:</h2>

      <ul>
      <% @breed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breeds/edit.html.erb
<h1>Editing Breed</h1>

<%= render 'form' %>

<%= link_to 'Show', @breed %> |
<%= link_to 'Back', breeds_path %>

app/views/breeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Breeds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breeds.each do |breed| %>
      <tr>
        <td><%= breed.name %></td>
        <td><%= breed.description %></td>
        <td><%= link_to 'Show', breed %></td>
        <td><%= link_to 'Edit', edit_breed_path(breed) %></td>
        <td><%= link_to 'Destroy', breed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breed', new_breed_path %>

app/views/breeds/new.html.erb
<h1>New Breed</h1>

<%= render 'form' %>

<%= link_to 'Back', breeds_path %>

app/views/breeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @breed.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @breed.description %>
</p>

<%= link_to 'Edit', edit_breed_path(@breed) %> |
<%= link_to 'Back', breeds_path %>

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class='field'>
    <%= f.collection_select(:breed_id, Breed.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :picture %>
    <%= f.hidden_field(:picture_cache) %>
    <%= f.file_field(:picture) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<header>
<h1>Dogs</h1>
<%= link_to 'New Dog', new_dog_path, :class => "header_links" %>
<%= link_to 'Breeds', breeds_path, :class => "header_links" %>
</header>

<p id="notice"><%= notice %></p>

<p>Sort:
  <%= link_to "by name", dogs_path(sort_by: :name) %>
  <%= link_to "by age", dogs_path(sort_by: :age) %>
</p>
<p>Filter:
  <%= link_to "dogs under 5yo", dogs_path(babies: :true) %>
  <%= link_to "dogs with pictures", dogs_path(pictures: :true) %>
</p>

<p>
	<% Breed.all.each do |b| %>
	  <%= link_to b.name, dogs_path(breed_id: b.id) %>
	<% end %>
	<%= link_to "All Breeds", dogs_path %>
</p>

<% @dogs.each do |dog| %>
  <div class="dog_box">
    <h3><%= link_to dog.name, dog %></h3>
    <%= image_tag(dog.picture_url(:standard))  unless dog.picture_url(:thumb).blank? %>
    <p>Age: <%= dog.age %></p>
    <p>Breed: <%= dog.breed.try(:name) %></p>
  </div>
<% end %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p><%= link_to '<< Back', dogs_path %></p>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>
<p>
	<strong>Age:</strong>
	<%= @dog.age %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Delete', @dog, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dogs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>